from enum import Enum


class SpotifyRequestQueryParamsPaths(str, Enum):
    VALUE_0 = "/me/albums"
    VALUE_1 = "/me/episodes"
    VALUE_10 = "/artists/:id/top-tracks"
    VALUE_11 = "/audio-features"
    VALUE_12 = "/browse/featured-playlists"
    VALUE_13 = "/browse/new-releases"
    VALUE_14 = "/episodes"
    VALUE_15 = "/recommendations"
    VALUE_16 = "/me/albums/contains"
    VALUE_17 = "/me/episodes/contains"
    VALUE_18 = "/me/following/contains"
    VALUE_19 = "/me/shows/contains"
    VALUE_2 = "/me/following"
    VALUE_20 = "/me/top/artists"
    VALUE_21 = "/me/top/tracks"
    VALUE_22 = "/me/tracks/contains"
    VALUE_23 = "/me/player"
    VALUE_24 = "/me/player/currently-playing"
    VALUE_25 = "/me/player/recently-played"
    VALUE_26 = "/me/playlists"
    VALUE_27 = "/playlists/:id/followers/contains"
    VALUE_28 = "/playlists/:id/tracks"
    VALUE_29 = "/playlists/:id"
    VALUE_3 = "/me/shows"
    VALUE_30 = "/search"
    VALUE_31 = "/shows"
    VALUE_32 = "/shows/:id/episodes"
    VALUE_33 = "/tracks"
    VALUE_34 = "/tracks/:id"
    VALUE_35 = "/me/player/pause"
    VALUE_36 = "/me/player/play"
    VALUE_37 = "/me/player/repeat"
    VALUE_38 = "/me/player/seek"
    VALUE_39 = "/me/player/shuffle"
    VALUE_4 = "/me/tracks"
    VALUE_40 = "/me/player/volume"
    VALUE_41 = "/me/player/next"
    VALUE_42 = "/me/player/previous"
    VALUE_43 = "/me/player/queue"
    VALUE_5 = "/albums"
    VALUE_6 = "/albums/:id"
    VALUE_7 = "/albums/:id/tracks"
    VALUE_8 = "/artists"
    VALUE_9 = "/artists/:id/albums"

    def __str__(self) -> str:
        return str(self.value)
